var os = require("os");
console.log(Math.random());
const name="John";
const age=10;
const num=2;
//console.log("%s is %d years old",name,age);
//console.error(new Error("This is a wrong method"));
//console.warn("This is a warning %d message",num);
//console.debug("This is a debug message");
console.log(os.hostname());
console.log(os.homedir());
console.log(os.freemem());
console.log(os.arch());
console.log(os.uptime());
console.log(os.cpus());